#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 146
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 2
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 5

enum {
  anon_sym_LPAREN = 1,
  anon_sym_COMMA = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACK = 4,
  anon_sym_RBRACK = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_code = 8,
  anon_sym_Entity = 9,
  anon_sym_as = 10,
  anon_sym_use = 11,
  anon_sym_pub = 12,
  anon_sym_fn = 13,
  sym_ident = 14,
  sym_template_call_ident = 15,
  anon_sym_DQUOTE = 16,
  anon_sym_DQUOTE2 = 17,
  sym_escape_sequence = 18,
  sym_line_comment = 19,
  sym__string_content = 20,
  sym_chirp_file = 21,
  sym__token_tree = 22,
  sym_argument = 23,
  sym__arguments = 24,
  sym_method = 25,
  sym_statement = 26,
  sym__statement_tail = 27,
  sym_path = 28,
  sym_import_item = 29,
  sym_import = 30,
  sym_parameters = 31,
  sym_fn = 32,
  sym_string_lit = 33,
  aux_sym_chirp_file_repeat1 = 34,
  aux_sym_chirp_file_repeat2 = 35,
  aux_sym__token_tree_repeat1 = 36,
  aux_sym_argument_repeat1 = 37,
  aux_sym__arguments_repeat1 = 38,
  aux_sym__statement_tail_repeat1 = 39,
  aux_sym__statement_tail_repeat2 = 40,
  aux_sym_import_repeat1 = 41,
  aux_sym_parameters_repeat1 = 42,
  aux_sym_string_lit_repeat1 = 43,
  anon_alias_sym_ident = 44,
  anon_alias_sym_string_lit = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_code] = "code",
  [anon_sym_Entity] = "Entity",
  [anon_sym_as] = "as",
  [anon_sym_use] = "use",
  [anon_sym_pub] = "pub",
  [anon_sym_fn] = "fn",
  [sym_ident] = "ident",
  [sym_template_call_ident] = "template_call_ident",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [sym_line_comment] = "line_comment",
  [sym__string_content] = "_string_content",
  [sym_chirp_file] = "chirp_file",
  [sym__token_tree] = "_token_tree",
  [sym_argument] = "argument",
  [sym__arguments] = "_arguments",
  [sym_method] = "method",
  [sym_statement] = "statement",
  [sym__statement_tail] = "_statement_tail",
  [sym_path] = "path",
  [sym_import_item] = "import_item",
  [sym_import] = "import",
  [sym_parameters] = "parameters",
  [sym_fn] = "fn",
  [sym_string_lit] = "string_lit",
  [aux_sym_chirp_file_repeat1] = "chirp_file_repeat1",
  [aux_sym_chirp_file_repeat2] = "chirp_file_repeat2",
  [aux_sym__token_tree_repeat1] = "_token_tree_repeat1",
  [aux_sym_argument_repeat1] = "argument_repeat1",
  [aux_sym__arguments_repeat1] = "_arguments_repeat1",
  [aux_sym__statement_tail_repeat1] = "_statement_tail_repeat1",
  [aux_sym__statement_tail_repeat2] = "_statement_tail_repeat2",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_string_lit_repeat1] = "string_lit_repeat1",
  [anon_alias_sym_ident] = "ident",
  [anon_alias_sym_string_lit] = "string_lit",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_Entity] = anon_sym_Entity,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_fn] = anon_sym_fn,
  [sym_ident] = sym_ident,
  [sym_template_call_ident] = sym_template_call_ident,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_line_comment] = sym_line_comment,
  [sym__string_content] = sym__string_content,
  [sym_chirp_file] = sym_chirp_file,
  [sym__token_tree] = sym__token_tree,
  [sym_argument] = sym_argument,
  [sym__arguments] = sym__arguments,
  [sym_method] = sym_method,
  [sym_statement] = sym_statement,
  [sym__statement_tail] = sym__statement_tail,
  [sym_path] = sym_path,
  [sym_import_item] = sym_import_item,
  [sym_import] = sym_import,
  [sym_parameters] = sym_parameters,
  [sym_fn] = sym_fn,
  [sym_string_lit] = sym_string_lit,
  [aux_sym_chirp_file_repeat1] = aux_sym_chirp_file_repeat1,
  [aux_sym_chirp_file_repeat2] = aux_sym_chirp_file_repeat2,
  [aux_sym__token_tree_repeat1] = aux_sym__token_tree_repeat1,
  [aux_sym_argument_repeat1] = aux_sym_argument_repeat1,
  [aux_sym__arguments_repeat1] = aux_sym__arguments_repeat1,
  [aux_sym__statement_tail_repeat1] = aux_sym__statement_tail_repeat1,
  [aux_sym__statement_tail_repeat2] = aux_sym__statement_tail_repeat2,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_string_lit_repeat1] = aux_sym_string_lit_repeat1,
  [anon_alias_sym_ident] = anon_alias_sym_ident,
  [anon_alias_sym_string_lit] = anon_alias_sym_string_lit,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_template_call_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_chirp_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token_tree] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_chirp_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chirp_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__token_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_ident] = {
    .visible = true,
    .named = false,
  },
  [anon_alias_sym_string_lit] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_entity_name = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_entity_name] = "entity_name",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_entity_name, 0},
  [1] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = anon_alias_sym_ident,
  },
  [4] = {
    [0] = anon_alias_sym_string_lit,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string_lit, 2,
    sym_string_lit,
    anon_alias_sym_string_lit,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 7,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 7,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 27,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 36,
  [37] = 29,
  [38] = 38,
  [39] = 39,
  [40] = 36,
  [41] = 35,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 38,
  [62] = 62,
  [63] = 63,
  [64] = 43,
  [65] = 42,
  [66] = 66,
  [67] = 67,
  [68] = 44,
  [69] = 69,
  [70] = 70,
  [71] = 66,
  [72] = 70,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 75,
  [77] = 77,
  [78] = 73,
  [79] = 79,
  [80] = 80,
  [81] = 80,
  [82] = 47,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 83,
  [87] = 85,
  [88] = 88,
  [89] = 83,
  [90] = 90,
  [91] = 84,
  [92] = 92,
  [93] = 85,
  [94] = 49,
  [95] = 95,
  [96] = 96,
  [97] = 28,
  [98] = 30,
  [99] = 58,
  [100] = 51,
  [101] = 53,
  [102] = 102,
  [103] = 57,
  [104] = 55,
  [105] = 105,
  [106] = 52,
  [107] = 44,
  [108] = 108,
  [109] = 59,
  [110] = 56,
  [111] = 111,
  [112] = 112,
  [113] = 43,
  [114] = 42,
  [115] = 115,
  [116] = 116,
  [117] = 54,
  [118] = 105,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 132,
  [141] = 141,
  [142] = 142,
  [143] = 143,
  [144] = 122,
  [145] = 141,
};

static inline bool sym_ident_character_set_1(int32_t c) {
  return (c < ','
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '\''
        ? (c >= ' ' && c <= '"')
        : c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_line_comment_character_set_1(int32_t c) {
  return (c < ','
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= '"' || (c >= '\'' && c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '\'') ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(26);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == '{') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 27:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(33);
      if (lookahead == ',') ADVANCE(32);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(35);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(36);
      if (lookahead == '}') ADVANCE(37);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == 'u') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(28)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_code);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Entity);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_Entity);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_use);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_pub);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_fn);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == '/') ADVANCE(64);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'b') ADVANCE(46);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'd') ADVANCE(53);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(44);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(39);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(60);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(59);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(48);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'o') ADVANCE(51);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 's') ADVANCE(52);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(54);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(62);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'u') ADVANCE(50);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'y') ADVANCE(41);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(69);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(66);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_template_call_ident);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_template_call_ident);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 29},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 28},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 29},
  [46] = {.lex_state = 29},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 2},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 1, .external_lex_state = 1},
  [70] = {.lex_state = 1, .external_lex_state = 1},
  [71] = {.lex_state = 2},
  [72] = {.lex_state = 1, .external_lex_state = 1},
  [73] = {.lex_state = 1, .external_lex_state = 1},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 2},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 1, .external_lex_state = 1},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 2},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 2},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 2},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 2},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 2},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 2},
  [145] = {.lex_state = 0},
};

enum {
  ts_external_token__string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__string_content] = sym__string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__string_content] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_Entity] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym__string_content] = ACTIONS(1),
  },
  [1] = {
    [sym_chirp_file] = STATE(129),
    [sym_statement] = STATE(123),
    [sym_import] = STATE(2),
    [sym_fn] = STATE(3),
    [sym_string_lit] = STATE(84),
    [aux_sym_chirp_file_repeat1] = STATE(2),
    [aux_sym_chirp_file_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_code] = ACTIONS(7),
    [anon_sym_Entity] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_pub] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_template_call_ident] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_string_lit,
    STATE(136), 1,
      sym_statement,
    STATE(4), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
  [45] = 12,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_string_lit,
    STATE(136), 1,
      sym_statement,
    STATE(18), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [83] = 12,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      sym_string_lit,
    STATE(127), 1,
      sym_statement,
    STATE(18), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [121] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      anon_sym_COMMA,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(40), 1,
      anon_sym_LBRACE,
    ACTIONS(43), 1,
      sym_ident,
    ACTIONS(46), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_lit,
    STATE(5), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
    ACTIONS(35), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [155] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_use,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
    ACTIONS(51), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [178] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 1,
      anon_sym_RPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_lit,
    STATE(87), 1,
      sym_argument,
    STATE(16), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [210] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(68), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_string_lit,
    STATE(93), 1,
      sym_argument,
    STATE(16), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [242] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      anon_sym_COMMA,
    ACTIONS(72), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_string_lit,
    STATE(13), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [274] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      anon_sym_RBRACK,
    ACTIONS(74), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym_string_lit,
    STATE(15), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [306] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(72), 1,
      anon_sym_RPAREN,
    ACTIONS(76), 1,
      anon_sym_COMMA,
    STATE(33), 1,
      sym_string_lit,
    STATE(12), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [338] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    ACTIONS(80), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_string_lit,
    STATE(5), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [370] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    ACTIONS(80), 1,
      anon_sym_RBRACE,
    STATE(33), 1,
      sym_string_lit,
    STATE(5), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [402] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(82), 1,
      anon_sym_RPAREN,
    STATE(33), 1,
      sym_string_lit,
    STATE(85), 1,
      sym_argument,
    STATE(16), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [434] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    ACTIONS(78), 1,
      anon_sym_COMMA,
    ACTIONS(80), 1,
      anon_sym_RBRACK,
    STATE(33), 1,
      sym_string_lit,
    STATE(5), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [466] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_lit,
    ACTIONS(84), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(17), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [496] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(86), 1,
      anon_sym_LPAREN,
    ACTIONS(91), 1,
      anon_sym_LBRACK,
    ACTIONS(94), 1,
      anon_sym_LBRACE,
    ACTIONS(97), 1,
      sym_ident,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_lit,
    ACTIONS(89), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
    STATE(17), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [526] = 6,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(107), 1,
      anon_sym_pub,
    ACTIONS(110), 1,
      anon_sym_fn,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(18), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    ACTIONS(105), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [550] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(56), 1,
      anon_sym_LPAREN,
    ACTIONS(60), 1,
      anon_sym_LBRACK,
    ACTIONS(62), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      sym_ident,
    ACTIONS(66), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_string_lit,
    STATE(111), 1,
      sym_argument,
    STATE(16), 2,
      sym__token_tree,
      aux_sym_argument_repeat1,
  [579] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      sym_ident,
    ACTIONS(113), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [596] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(117), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(119), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [613] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(123), 1,
      sym_ident,
    ACTIONS(121), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [630] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(125), 1,
      anon_sym_RBRACE,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [659] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [688] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(139), 1,
      sym_ident,
    ACTIONS(137), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [705] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(143), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [722] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(23), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [751] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(149), 1,
      sym_ident,
    ACTIONS(147), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [768] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [797] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(155), 1,
      sym_ident,
    ACTIONS(153), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [814] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [843] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(24), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [872] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(161), 1,
      sym_ident,
    ACTIONS(159), 8,
      anon_sym_LPAREN,
      anon_sym_COMMA,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
  [889] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(157), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [918] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(163), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(31), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [947] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(165), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [976] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(167), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(40), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1005] = 6,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    STATE(56), 1,
      sym__statement_tail,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(175), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1028] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      anon_sym_RBRACE,
    ACTIONS(179), 1,
      anon_sym_code,
    ACTIONS(182), 1,
      anon_sym_Entity,
    ACTIONS(185), 1,
      sym_ident,
    ACTIONS(188), 1,
      sym_template_call_ident,
    ACTIONS(191), 1,
      anon_sym_DQUOTE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1057] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1086] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(127), 1,
      anon_sym_code,
    ACTIONS(129), 1,
      anon_sym_Entity,
    ACTIONS(131), 1,
      sym_ident,
    ACTIONS(133), 1,
      sym_template_call_ident,
    ACTIONS(196), 1,
      anon_sym_RBRACE,
    STATE(91), 1,
      sym_string_lit,
    STATE(34), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1115] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(198), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(200), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1131] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(202), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(204), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1147] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(206), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(208), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1163] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(210), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(212), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1179] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(216), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1195] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(218), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(222), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1212] = 8,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    STATE(84), 1,
      sym_string_lit,
    STATE(134), 1,
      sym_statement,
  [1237] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(224), 1,
      anon_sym_LBRACE,
    ACTIONS(226), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(228), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1254] = 8,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    STATE(84), 1,
      sym_string_lit,
    STATE(131), 1,
      sym_statement,
  [1279] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(230), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(232), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1293] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(234), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(236), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1307] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(238), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(240), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1321] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(226), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(228), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1335] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(242), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(244), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1349] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(246), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(248), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1363] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(220), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(222), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1377] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(250), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(252), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1391] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(173), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(175), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1405] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
    ACTIONS(256), 1,
      anon_sym_RPAREN,
    ACTIONS(258), 1,
      sym_ident,
    STATE(63), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1422] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    STATE(110), 1,
      sym__statement_tail,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1439] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(264), 1,
      anon_sym_LPAREN,
    ACTIONS(267), 1,
      anon_sym_RPAREN,
    ACTIONS(269), 1,
      sym_ident,
    STATE(62), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1456] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(254), 1,
      anon_sym_LPAREN,
    ACTIONS(258), 1,
      sym_ident,
    ACTIONS(272), 1,
      anon_sym_RPAREN,
    STATE(62), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1473] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1483] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1493] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(274), 1,
      anon_sym_RPAREN,
    ACTIONS(276), 1,
      sym_ident,
    STATE(75), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1507] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(278), 1,
      anon_sym_RPAREN,
    ACTIONS(280), 1,
      sym_ident,
    STATE(67), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1521] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(206), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1531] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(283), 1,
      anon_sym_DQUOTE2,
    STATE(69), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(285), 2,
      sym__string_content,
      sym_escape_sequence,
  [1545] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(288), 1,
      anon_sym_DQUOTE2,
    STATE(73), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(290), 2,
      sym__string_content,
      sym_escape_sequence,
  [1559] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(276), 1,
      sym_ident,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    STATE(76), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1573] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(294), 1,
      anon_sym_DQUOTE2,
    STATE(78), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(296), 2,
      sym__string_content,
      sym_escape_sequence,
  [1587] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(298), 1,
      anon_sym_DQUOTE2,
    STATE(69), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(300), 2,
      sym__string_content,
      sym_escape_sequence,
  [1601] = 5,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(302), 1,
      sym_ident,
    STATE(120), 1,
      sym_path,
    STATE(124), 1,
      sym_string_lit,
  [1617] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(276), 1,
      sym_ident,
    ACTIONS(304), 1,
      anon_sym_RPAREN,
    STATE(67), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1631] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(276), 1,
      sym_ident,
    ACTIONS(306), 1,
      anon_sym_RPAREN,
    STATE(67), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1645] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(308), 1,
      anon_sym_LPAREN,
    ACTIONS(310), 1,
      anon_sym_RPAREN,
    ACTIONS(312), 1,
      sym_ident,
    STATE(112), 1,
      sym__arguments,
  [1661] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(314), 1,
      anon_sym_DQUOTE2,
    STATE(69), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(300), 2,
      sym__string_content,
      sym_escape_sequence,
  [1675] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__arguments_repeat1,
  [1688] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    STATE(109), 1,
      sym__statement_tail,
  [1701] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    STATE(59), 1,
      sym__statement_tail,
  [1714] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(321), 1,
      anon_sym_LBRACE,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1725] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(325), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__arguments_repeat1,
  [1738] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(260), 1,
      anon_sym_LPAREN,
    ACTIONS(262), 1,
      anon_sym_LBRACE,
    STATE(99), 1,
      sym__statement_tail,
  [1751] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym__arguments_repeat1,
  [1764] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(329), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__arguments_repeat1,
  [1777] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym__arguments_repeat1,
  [1790] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
  [1803] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(337), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__arguments_repeat1,
  [1816] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(341), 1,
      sym_ident,
    ACTIONS(339), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1827] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      anon_sym_LPAREN,
    ACTIONS(171), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym__statement_tail,
  [1840] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(345), 1,
      sym_ident,
    ACTIONS(343), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1851] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(323), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym__arguments_repeat1,
  [1864] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1875] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(333), 1,
      anon_sym_COMMA,
    ACTIONS(351), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym_parameters_repeat1,
  [1888] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(353), 1,
      anon_sym_COMMA,
    ACTIONS(356), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      aux_sym_parameters_repeat1,
  [1901] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(147), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1909] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(153), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1917] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(250), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1925] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(230), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1933] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(238), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1941] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(358), 1,
      anon_sym_LPAREN,
    STATE(121), 1,
      sym_parameters,
  [1951] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(220), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1959] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(242), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1967] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(360), 1,
      anon_sym_LPAREN,
    STATE(38), 1,
      sym__arguments,
  [1977] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1985] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(206), 1,
      anon_sym_RPAREN,
    ACTIONS(208), 1,
      sym_ident,
  [1995] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(356), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2003] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(173), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2011] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(246), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2019] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(319), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [2027] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(362), 1,
      anon_sym_RPAREN,
    ACTIONS(364), 1,
      sym_ident,
  [2037] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(202), 1,
      anon_sym_RPAREN,
    ACTIONS(204), 1,
      sym_ident,
  [2047] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(198), 1,
      anon_sym_RPAREN,
    ACTIONS(200), 1,
      sym_ident,
  [2057] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
    ACTIONS(368), 1,
      sym_ident,
  [2067] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(358), 1,
      anon_sym_LPAREN,
    STATE(143), 1,
      sym_parameters,
  [2077] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(226), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2085] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(370), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym__arguments,
  [2095] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(372), 1,
      anon_sym_LBRACE,
  [2102] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(374), 1,
      anon_sym_LPAREN,
  [2109] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(376), 1,
      anon_sym_LBRACE,
  [2116] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(378), 1,
      sym_ident,
  [2123] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [2130] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(380), 1,
      anon_sym_LPAREN,
  [2137] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(382), 1,
      sym_ident,
  [2144] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(384), 1,
      sym_ident,
  [2151] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(386), 1,
      ts_builtin_sym_end,
  [2158] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(388), 1,
      anon_sym_RPAREN,
  [2165] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(390), 1,
      ts_builtin_sym_end,
  [2172] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(392), 1,
      anon_sym_LBRACE,
  [2179] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(394), 1,
      anon_sym_RBRACE,
  [2186] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(396), 1,
      anon_sym_RPAREN,
  [2193] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(398), 1,
      sym_ident,
  [2200] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(400), 1,
      anon_sym_RBRACE,
  [2207] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(402), 1,
      sym_ident,
  [2214] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
  [2221] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(404), 1,
      anon_sym_as,
  [2228] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(406), 1,
      sym_ident,
  [2235] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(408), 1,
      anon_sym_fn,
  [2242] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(410), 1,
      anon_sym_RPAREN,
  [2249] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(412), 1,
      anon_sym_LPAREN,
  [2256] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(414), 1,
      anon_sym_LBRACE,
  [2263] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(416), 1,
      anon_sym_LBRACE,
  [2270] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(418), 1,
      sym_ident,
  [2277] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(420), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 83,
  [SMALL_STATE(5)] = 121,
  [SMALL_STATE(6)] = 155,
  [SMALL_STATE(7)] = 178,
  [SMALL_STATE(8)] = 210,
  [SMALL_STATE(9)] = 242,
  [SMALL_STATE(10)] = 274,
  [SMALL_STATE(11)] = 306,
  [SMALL_STATE(12)] = 338,
  [SMALL_STATE(13)] = 370,
  [SMALL_STATE(14)] = 402,
  [SMALL_STATE(15)] = 434,
  [SMALL_STATE(16)] = 466,
  [SMALL_STATE(17)] = 496,
  [SMALL_STATE(18)] = 526,
  [SMALL_STATE(19)] = 550,
  [SMALL_STATE(20)] = 579,
  [SMALL_STATE(21)] = 596,
  [SMALL_STATE(22)] = 613,
  [SMALL_STATE(23)] = 630,
  [SMALL_STATE(24)] = 659,
  [SMALL_STATE(25)] = 688,
  [SMALL_STATE(26)] = 705,
  [SMALL_STATE(27)] = 722,
  [SMALL_STATE(28)] = 751,
  [SMALL_STATE(29)] = 768,
  [SMALL_STATE(30)] = 797,
  [SMALL_STATE(31)] = 814,
  [SMALL_STATE(32)] = 843,
  [SMALL_STATE(33)] = 872,
  [SMALL_STATE(34)] = 889,
  [SMALL_STATE(35)] = 918,
  [SMALL_STATE(36)] = 947,
  [SMALL_STATE(37)] = 976,
  [SMALL_STATE(38)] = 1005,
  [SMALL_STATE(39)] = 1028,
  [SMALL_STATE(40)] = 1057,
  [SMALL_STATE(41)] = 1086,
  [SMALL_STATE(42)] = 1115,
  [SMALL_STATE(43)] = 1131,
  [SMALL_STATE(44)] = 1147,
  [SMALL_STATE(45)] = 1163,
  [SMALL_STATE(46)] = 1179,
  [SMALL_STATE(47)] = 1195,
  [SMALL_STATE(48)] = 1212,
  [SMALL_STATE(49)] = 1237,
  [SMALL_STATE(50)] = 1254,
  [SMALL_STATE(51)] = 1279,
  [SMALL_STATE(52)] = 1293,
  [SMALL_STATE(53)] = 1307,
  [SMALL_STATE(54)] = 1321,
  [SMALL_STATE(55)] = 1335,
  [SMALL_STATE(56)] = 1349,
  [SMALL_STATE(57)] = 1363,
  [SMALL_STATE(58)] = 1377,
  [SMALL_STATE(59)] = 1391,
  [SMALL_STATE(60)] = 1405,
  [SMALL_STATE(61)] = 1422,
  [SMALL_STATE(62)] = 1439,
  [SMALL_STATE(63)] = 1456,
  [SMALL_STATE(64)] = 1473,
  [SMALL_STATE(65)] = 1483,
  [SMALL_STATE(66)] = 1493,
  [SMALL_STATE(67)] = 1507,
  [SMALL_STATE(68)] = 1521,
  [SMALL_STATE(69)] = 1531,
  [SMALL_STATE(70)] = 1545,
  [SMALL_STATE(71)] = 1559,
  [SMALL_STATE(72)] = 1573,
  [SMALL_STATE(73)] = 1587,
  [SMALL_STATE(74)] = 1601,
  [SMALL_STATE(75)] = 1617,
  [SMALL_STATE(76)] = 1631,
  [SMALL_STATE(77)] = 1645,
  [SMALL_STATE(78)] = 1661,
  [SMALL_STATE(79)] = 1675,
  [SMALL_STATE(80)] = 1688,
  [SMALL_STATE(81)] = 1701,
  [SMALL_STATE(82)] = 1714,
  [SMALL_STATE(83)] = 1725,
  [SMALL_STATE(84)] = 1738,
  [SMALL_STATE(85)] = 1751,
  [SMALL_STATE(86)] = 1764,
  [SMALL_STATE(87)] = 1777,
  [SMALL_STATE(88)] = 1790,
  [SMALL_STATE(89)] = 1803,
  [SMALL_STATE(90)] = 1816,
  [SMALL_STATE(91)] = 1827,
  [SMALL_STATE(92)] = 1840,
  [SMALL_STATE(93)] = 1851,
  [SMALL_STATE(94)] = 1864,
  [SMALL_STATE(95)] = 1875,
  [SMALL_STATE(96)] = 1888,
  [SMALL_STATE(97)] = 1901,
  [SMALL_STATE(98)] = 1909,
  [SMALL_STATE(99)] = 1917,
  [SMALL_STATE(100)] = 1925,
  [SMALL_STATE(101)] = 1933,
  [SMALL_STATE(102)] = 1941,
  [SMALL_STATE(103)] = 1951,
  [SMALL_STATE(104)] = 1959,
  [SMALL_STATE(105)] = 1967,
  [SMALL_STATE(106)] = 1977,
  [SMALL_STATE(107)] = 1985,
  [SMALL_STATE(108)] = 1995,
  [SMALL_STATE(109)] = 2003,
  [SMALL_STATE(110)] = 2011,
  [SMALL_STATE(111)] = 2019,
  [SMALL_STATE(112)] = 2027,
  [SMALL_STATE(113)] = 2037,
  [SMALL_STATE(114)] = 2047,
  [SMALL_STATE(115)] = 2057,
  [SMALL_STATE(116)] = 2067,
  [SMALL_STATE(117)] = 2077,
  [SMALL_STATE(118)] = 2085,
  [SMALL_STATE(119)] = 2095,
  [SMALL_STATE(120)] = 2102,
  [SMALL_STATE(121)] = 2109,
  [SMALL_STATE(122)] = 2116,
  [SMALL_STATE(123)] = 2123,
  [SMALL_STATE(124)] = 2130,
  [SMALL_STATE(125)] = 2137,
  [SMALL_STATE(126)] = 2144,
  [SMALL_STATE(127)] = 2151,
  [SMALL_STATE(128)] = 2158,
  [SMALL_STATE(129)] = 2165,
  [SMALL_STATE(130)] = 2172,
  [SMALL_STATE(131)] = 2179,
  [SMALL_STATE(132)] = 2186,
  [SMALL_STATE(133)] = 2193,
  [SMALL_STATE(134)] = 2200,
  [SMALL_STATE(135)] = 2207,
  [SMALL_STATE(136)] = 2214,
  [SMALL_STATE(137)] = 2221,
  [SMALL_STATE(138)] = 2228,
  [SMALL_STATE(139)] = 2235,
  [SMALL_STATE(140)] = 2242,
  [SMALL_STATE(141)] = 2249,
  [SMALL_STATE(142)] = 2256,
  [SMALL_STATE(143)] = 2263,
  [SMALL_STATE(144)] = 2270,
  [SMALL_STATE(145)] = 2277,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 1),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 2),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(11),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(22),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(70),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2), SHIFT_REPEAT(74),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2), SHIFT_REPEAT(11),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2),
  [91] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2), SHIFT_REPEAT(10),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2), SHIFT_REPEAT(9),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_argument_repeat1, 2), SHIFT_REPEAT(22),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_repeat1, 2), SHIFT_REPEAT(70),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [107] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(139),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(138),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 2),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 3),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 3),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(145),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 2),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 2),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 3),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 4),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2),
  [179] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(145),
  [182] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(81),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(91),
  [188] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(105),
  [191] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(72),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 4),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 4),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 3),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 2),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 7),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 7),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 2),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 3),
  [228] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 3),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 6),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 6),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 5),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 5),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 4),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 4),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 4),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, .production_id = 1),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, .production_id = 1),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [264] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(126),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(90),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat1, 2),
  [280] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat1, 2), SHIFT_REPEAT(77),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2),
  [285] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2), SHIFT_REPEAT(69),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [302] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, .production_id = 2),
  [312] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 1, .production_id = 2),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2), SHIFT_REPEAT(19),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 1),
  [341] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 1),
  [343] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [345] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 5),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [353] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(135),
  [356] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 2, .production_id = 2),
  [364] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 2, .production_id = 2),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [368] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [372] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [378] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [382] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [384] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 3),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [390] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [392] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [396] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [398] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [402] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [406] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [408] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [410] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [414] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [418] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_chirp_external_scanner_create(void);
void tree_sitter_chirp_external_scanner_destroy(void *);
bool tree_sitter_chirp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_chirp_external_scanner_serialize(void *, char *);
void tree_sitter_chirp_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chirp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_chirp_external_scanner_create,
      tree_sitter_chirp_external_scanner_destroy,
      tree_sitter_chirp_external_scanner_scan,
      tree_sitter_chirp_external_scanner_serialize,
      tree_sitter_chirp_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
