#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 145
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 2
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 5

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COMMA = 7,
  anon_sym_code = 8,
  anon_sym_Entity = 9,
  anon_sym_as = 10,
  anon_sym_use = 11,
  anon_sym_pub = 12,
  anon_sym_fn = 13,
  sym_ident = 14,
  sym_template_call_ident = 15,
  anon_sym_DQUOTE = 16,
  anon_sym_DQUOTE2 = 17,
  sym_escape_sequence = 18,
  sym_line_comment = 19,
  sym__string_content = 20,
  sym_chirp_file = 21,
  sym__token_tree = 22,
  sym_argument = 23,
  sym__arguments = 24,
  sym_method = 25,
  sym_statement = 26,
  sym__statement_tail = 27,
  sym_path = 28,
  sym_import_item = 29,
  sym_import = 30,
  sym_parameters = 31,
  sym_fn = 32,
  sym_string_lit = 33,
  aux_sym_chirp_file_repeat1 = 34,
  aux_sym_chirp_file_repeat2 = 35,
  aux_sym__token_tree_repeat1 = 36,
  aux_sym__arguments_repeat1 = 37,
  aux_sym__statement_tail_repeat1 = 38,
  aux_sym__statement_tail_repeat2 = 39,
  aux_sym_import_repeat1 = 40,
  aux_sym_parameters_repeat1 = 41,
  aux_sym_string_lit_repeat1 = 42,
  anon_alias_sym_ident = 43,
  anon_alias_sym_string_lit = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_code] = "code",
  [anon_sym_Entity] = "Entity",
  [anon_sym_as] = "as",
  [anon_sym_use] = "use",
  [anon_sym_pub] = "pub",
  [anon_sym_fn] = "fn",
  [sym_ident] = "ident",
  [sym_template_call_ident] = "template_call_ident",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [sym_line_comment] = "line_comment",
  [sym__string_content] = "_string_content",
  [sym_chirp_file] = "chirp_file",
  [sym__token_tree] = "_token_tree",
  [sym_argument] = "argument",
  [sym__arguments] = "_arguments",
  [sym_method] = "method",
  [sym_statement] = "statement",
  [sym__statement_tail] = "_statement_tail",
  [sym_path] = "path",
  [sym_import_item] = "import_item",
  [sym_import] = "import",
  [sym_parameters] = "parameters",
  [sym_fn] = "fn",
  [sym_string_lit] = "string_lit",
  [aux_sym_chirp_file_repeat1] = "chirp_file_repeat1",
  [aux_sym_chirp_file_repeat2] = "chirp_file_repeat2",
  [aux_sym__token_tree_repeat1] = "_token_tree_repeat1",
  [aux_sym__arguments_repeat1] = "_arguments_repeat1",
  [aux_sym__statement_tail_repeat1] = "_statement_tail_repeat1",
  [aux_sym__statement_tail_repeat2] = "_statement_tail_repeat2",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_string_lit_repeat1] = "string_lit_repeat1",
  [anon_alias_sym_ident] = "ident",
  [anon_alias_sym_string_lit] = "string_lit",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_Entity] = anon_sym_Entity,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_fn] = anon_sym_fn,
  [sym_ident] = sym_ident,
  [sym_template_call_ident] = sym_template_call_ident,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_line_comment] = sym_line_comment,
  [sym__string_content] = sym__string_content,
  [sym_chirp_file] = sym_chirp_file,
  [sym__token_tree] = sym__token_tree,
  [sym_argument] = sym_argument,
  [sym__arguments] = sym__arguments,
  [sym_method] = sym_method,
  [sym_statement] = sym_statement,
  [sym__statement_tail] = sym__statement_tail,
  [sym_path] = sym_path,
  [sym_import_item] = sym_import_item,
  [sym_import] = sym_import,
  [sym_parameters] = sym_parameters,
  [sym_fn] = sym_fn,
  [sym_string_lit] = sym_string_lit,
  [aux_sym_chirp_file_repeat1] = aux_sym_chirp_file_repeat1,
  [aux_sym_chirp_file_repeat2] = aux_sym_chirp_file_repeat2,
  [aux_sym__token_tree_repeat1] = aux_sym__token_tree_repeat1,
  [aux_sym__arguments_repeat1] = aux_sym__arguments_repeat1,
  [aux_sym__statement_tail_repeat1] = aux_sym__statement_tail_repeat1,
  [aux_sym__statement_tail_repeat2] = aux_sym__statement_tail_repeat2,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_string_lit_repeat1] = aux_sym_string_lit_repeat1,
  [anon_alias_sym_ident] = anon_alias_sym_ident,
  [anon_alias_sym_string_lit] = anon_alias_sym_string_lit,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_template_call_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_chirp_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token_tree] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_chirp_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chirp_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__token_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_ident] = {
    .visible = true,
    .named = false,
  },
  [anon_alias_sym_string_lit] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_entity_name = 1,
  field_name = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_entity_name] = "entity_name",
  [field_name] = "name",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_entity_name, 0},
  [1] =
    {field_name, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [3] = {
    [0] = anon_alias_sym_ident,
  },
  [4] = {
    [0] = anon_alias_sym_string_lit,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string_lit, 2,
    sym_string_lit,
    anon_alias_sym_string_lit,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 7,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 12,
  [29] = 29,
  [30] = 25,
  [31] = 18,
  [32] = 15,
  [33] = 33,
  [34] = 33,
  [35] = 35,
  [36] = 29,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 22,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 63,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 67,
  [71] = 71,
  [72] = 44,
  [73] = 43,
  [74] = 71,
  [75] = 45,
  [76] = 76,
  [77] = 76,
  [78] = 78,
  [79] = 79,
  [80] = 49,
  [81] = 81,
  [82] = 78,
  [83] = 48,
  [84] = 84,
  [85] = 85,
  [86] = 78,
  [87] = 87,
  [88] = 88,
  [89] = 84,
  [90] = 85,
  [91] = 91,
  [92] = 88,
  [93] = 93,
  [94] = 84,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 21,
  [99] = 57,
  [100] = 19,
  [101] = 101,
  [102] = 102,
  [103] = 55,
  [104] = 97,
  [105] = 58,
  [106] = 106,
  [107] = 54,
  [108] = 53,
  [109] = 43,
  [110] = 110,
  [111] = 111,
  [112] = 52,
  [113] = 51,
  [114] = 44,
  [115] = 45,
  [116] = 56,
  [117] = 50,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 131,
  [143] = 121,
  [144] = 129,
};

static inline bool sym_ident_character_set_1(int32_t c) {
  return (c < ','
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '\''
        ? (c >= ' ' && c <= '"')
        : c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_line_comment_character_set_1(int32_t c) {
  return (c < ','
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= '"' || (c >= '\'' && c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '\'') ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(26);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == '{') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 27:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == 'u') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(28)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_code);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Entity);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_Entity);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_use);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_pub);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_fn);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == '/') ADVANCE(64);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'b') ADVANCE(46);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'd') ADVANCE(53);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(44);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(39);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(60);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(59);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(48);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'o') ADVANCE(51);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 's') ADVANCE(52);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(54);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(62);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'u') ADVANCE(50);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'y') ADVANCE(41);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(69);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(66);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_template_call_ident);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_template_call_ident);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 29},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 28},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 3},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 2},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 1, .external_lex_state = 1},
  [68] = {.lex_state = 1, .external_lex_state = 1},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 1, .external_lex_state = 1},
  [71] = {.lex_state = 1, .external_lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 1, .external_lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 2},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 2},
  [121] = {.lex_state = 2},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 2},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 2},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 2},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 2},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 2},
  [144] = {.lex_state = 0},
};

enum {
  ts_external_token__string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__string_content] = sym__string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__string_content] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_Entity] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym__string_content] = ACTIONS(1),
  },
  [1] = {
    [sym_chirp_file] = STATE(128),
    [sym_statement] = STATE(122),
    [sym_import] = STATE(2),
    [sym_fn] = STATE(5),
    [sym_string_lit] = STATE(88),
    [aux_sym_chirp_file_repeat1] = STATE(2),
    [aux_sym_chirp_file_repeat2] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_code] = ACTIONS(7),
    [anon_sym_Entity] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_pub] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [sym_ident] = ACTIONS(17),
    [sym_template_call_ident] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [sym_line_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_string_lit,
    STATE(135), 1,
      sym_statement,
    STATE(4), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
  [45] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(32), 1,
      anon_sym_LBRACK,
    ACTIONS(35), 1,
      anon_sym_LBRACE,
    ACTIONS(38), 1,
      sym_ident,
    ACTIONS(41), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string_lit,
    STATE(3), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
    ACTIONS(30), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [77] = 12,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_string_lit,
    STATE(127), 1,
      sym_statement,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [115] = 12,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(88), 1,
      sym_string_lit,
    STATE(135), 1,
      sym_statement,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [153] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(50), 1,
      anon_sym_use,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
    ACTIONS(48), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [176] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_RPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string_lit,
    STATE(84), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [208] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string_lit,
    ACTIONS(65), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    STATE(3), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [238] = 6,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(71), 1,
      anon_sym_pub,
    ACTIONS(74), 1,
      anon_sym_fn,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    ACTIONS(69), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [262] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_string_lit,
    STATE(89), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [294] = 10,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_string_lit,
    STATE(94), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [326] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(81), 1,
      anon_sym_RBRACE,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [355] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(91), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(93), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [372] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_string_lit,
    STATE(3), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [401] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(28), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [430] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(99), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [447] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(103), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(105), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [464] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(107), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [493] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(111), 1,
      sym_ident,
    ACTIONS(109), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [510] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      sym_ident,
    ACTIONS(113), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [527] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(119), 1,
      sym_ident,
    ACTIONS(117), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [544] = 6,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(54), 1,
      sym__statement_tail,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(127), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [567] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_string_lit,
    STATE(37), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [596] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(129), 1,
      anon_sym_RBRACK,
    STATE(16), 1,
      sym_string_lit,
    STATE(14), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [625] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(33), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [654] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(135), 1,
      sym_ident,
    ACTIONS(133), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [671] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(129), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_string_lit,
    STATE(40), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [700] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(137), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [729] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(139), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [758] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(34), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [787] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(29), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [816] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(12), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [845] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [874] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [903] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    STATE(16), 1,
      sym_string_lit,
    STATE(110), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [932] = 9,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(83), 1,
      anon_sym_code,
    ACTIONS(85), 1,
      anon_sym_Entity,
    ACTIONS(87), 1,
      sym_ident,
    ACTIONS(89), 1,
      sym_template_call_ident,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [961] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      anon_sym_RBRACE,
    STATE(16), 1,
      sym_string_lit,
    STATE(3), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [990] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(151), 1,
      sym_ident,
    ACTIONS(149), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [1007] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(153), 1,
      anon_sym_RBRACE,
    ACTIONS(155), 1,
      anon_sym_code,
    ACTIONS(158), 1,
      anon_sym_Entity,
    ACTIONS(161), 1,
      sym_ident,
    ACTIONS(164), 1,
      sym_template_call_ident,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
    STATE(92), 1,
      sym_string_lit,
    STATE(39), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1036] = 9,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_LBRACE,
    ACTIONS(61), 1,
      sym_ident,
    ACTIONS(63), 1,
      anon_sym_DQUOTE,
    ACTIONS(95), 1,
      anon_sym_RPAREN,
    STATE(16), 1,
      sym_string_lit,
    STATE(3), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [1065] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(170), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(172), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1081] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(174), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(176), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1097] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(178), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(180), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1113] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(182), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(184), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1129] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(186), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(188), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1145] = 8,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    STATE(88), 1,
      sym_string_lit,
    STATE(133), 1,
      sym_statement,
  [1170] = 8,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(9), 1,
      anon_sym_Entity,
    ACTIONS(17), 1,
      sym_ident,
    ACTIONS(19), 1,
      sym_template_call_ident,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    STATE(88), 1,
      sym_string_lit,
    STATE(136), 1,
      sym_statement,
  [1195] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(190), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(194), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1212] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(200), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1229] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(192), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(194), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1243] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(202), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(204), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1257] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(125), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(127), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1271] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(206), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(208), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1285] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(210), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(212), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1299] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(214), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(216), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1313] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(198), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(200), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1327] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(218), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(220), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1341] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(222), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(224), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1355] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    ACTIONS(229), 1,
      anon_sym_RPAREN,
    ACTIONS(231), 1,
      sym_ident,
    STATE(59), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1372] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    ACTIONS(236), 1,
      anon_sym_RPAREN,
    ACTIONS(238), 1,
      sym_ident,
    STATE(62), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1389] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_LPAREN,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(107), 1,
      sym__statement_tail,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1406] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(234), 1,
      anon_sym_LPAREN,
    ACTIONS(238), 1,
      sym_ident,
    ACTIONS(244), 1,
      anon_sym_RPAREN,
    STATE(59), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1423] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(246), 1,
      anon_sym_RPAREN,
    ACTIONS(248), 1,
      sym_ident,
    STATE(76), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1437] = 5,
    ACTIONS(21), 1,
      anon_sym_DQUOTE,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(250), 1,
      sym_ident,
    STATE(118), 1,
      sym_string_lit,
    STATE(125), 1,
      sym_path,
  [1453] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(252), 1,
      anon_sym_RPAREN,
    ACTIONS(254), 1,
      sym_ident,
    STATE(65), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1467] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      sym_ident,
    ACTIONS(257), 1,
      anon_sym_RPAREN,
    STATE(77), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1481] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(259), 1,
      anon_sym_DQUOTE2,
    STATE(71), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(261), 2,
      sym__string_content,
      sym_escape_sequence,
  [1495] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(263), 1,
      anon_sym_DQUOTE2,
    STATE(68), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(265), 2,
      sym__string_content,
      sym_escape_sequence,
  [1509] = 5,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
    ACTIONS(270), 1,
      anon_sym_RPAREN,
    ACTIONS(272), 1,
      sym_ident,
    STATE(106), 1,
      sym__arguments,
  [1525] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(274), 1,
      anon_sym_DQUOTE2,
    STATE(74), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(276), 2,
      sym__string_content,
      sym_escape_sequence,
  [1539] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(278), 1,
      anon_sym_DQUOTE2,
    STATE(68), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(280), 2,
      sym__string_content,
      sym_escape_sequence,
  [1553] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(182), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1563] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(178), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1573] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(282), 1,
      anon_sym_DQUOTE2,
    STATE(68), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(280), 2,
      sym__string_content,
      sym_escape_sequence,
  [1587] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(186), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1597] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      sym_ident,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    STATE(65), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1611] = 4,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(248), 1,
      sym_ident,
    ACTIONS(286), 1,
      anon_sym_RPAREN,
    STATE(65), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1625] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym__arguments_repeat1,
  [1638] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(292), 1,
      anon_sym_RPAREN,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_parameters_repeat1,
  [1651] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(297), 1,
      anon_sym_LBRACE,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1662] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(301), 1,
      sym_ident,
    ACTIONS(299), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym__arguments_repeat1,
  [1686] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(305), 1,
      anon_sym_LBRACE,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1697] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(82), 1,
      aux_sym__arguments_repeat1,
  [1710] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_LPAREN,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(112), 1,
      sym__statement_tail,
  [1723] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(91), 1,
      aux_sym__arguments_repeat1,
  [1736] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(311), 1,
      anon_sym_RPAREN,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    STATE(79), 1,
      aux_sym_parameters_repeat1,
  [1749] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_LPAREN,
    ACTIONS(242), 1,
      anon_sym_LBRACE,
    STATE(108), 1,
      sym__statement_tail,
  [1762] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(315), 1,
      anon_sym_RPAREN,
    STATE(86), 1,
      aux_sym__arguments_repeat1,
  [1775] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym__statement_tail,
  [1788] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(317), 1,
      anon_sym_RPAREN,
    ACTIONS(319), 1,
      anon_sym_COMMA,
    STATE(91), 1,
      aux_sym__arguments_repeat1,
  [1801] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(121), 1,
      anon_sym_LPAREN,
    ACTIONS(123), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym__statement_tail,
  [1814] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      anon_sym_RPAREN,
    STATE(87), 1,
      aux_sym_parameters_repeat1,
  [1827] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RPAREN,
    STATE(78), 1,
      aux_sym__arguments_repeat1,
  [1840] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(328), 1,
      sym_ident,
    ACTIONS(326), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1851] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(330), 1,
      anon_sym_LPAREN,
    STATE(139), 1,
      sym_parameters,
  [1861] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(332), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym__arguments,
  [1871] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(117), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1879] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(218), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1887] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(109), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1895] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(334), 1,
      anon_sym_RPAREN,
    ACTIONS(336), 1,
      sym_ident,
  [1905] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(292), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1913] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(214), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1921] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(338), 1,
      anon_sym_LPAREN,
    STATE(61), 1,
      sym__arguments,
  [1931] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(222), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1939] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(340), 1,
      anon_sym_RPAREN,
    ACTIONS(342), 1,
      sym_ident,
  [1949] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(210), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1957] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(206), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1965] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(178), 1,
      anon_sym_RPAREN,
    ACTIONS(180), 1,
      sym_ident,
  [1975] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(317), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1983] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(330), 1,
      anon_sym_LPAREN,
    STATE(119), 1,
      sym_parameters,
  [1993] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(125), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2001] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(202), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2009] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(182), 1,
      anon_sym_RPAREN,
    ACTIONS(184), 1,
      sym_ident,
  [2019] = 3,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(186), 1,
      anon_sym_RPAREN,
    ACTIONS(188), 1,
      sym_ident,
  [2029] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(198), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2037] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(192), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [2045] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(344), 1,
      anon_sym_LPAREN,
  [2052] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(346), 1,
      anon_sym_LBRACE,
  [2059] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(348), 1,
      sym_ident,
  [2066] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(350), 1,
      sym_ident,
  [2073] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
  [2080] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(352), 1,
      anon_sym_as,
  [2087] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(354), 1,
      anon_sym_LBRACE,
  [2094] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(356), 1,
      anon_sym_LPAREN,
  [2101] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(358), 1,
      sym_ident,
  [2108] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(360), 1,
      ts_builtin_sym_end,
  [2115] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(362), 1,
      ts_builtin_sym_end,
  [2122] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(364), 1,
      anon_sym_LPAREN,
  [2129] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(366), 1,
      anon_sym_RPAREN,
  [2136] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(368), 1,
      anon_sym_RPAREN,
  [2143] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(370), 1,
      anon_sym_LBRACE,
  [2150] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(372), 1,
      anon_sym_RBRACE,
  [2157] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(374), 1,
      sym_ident,
  [2164] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
  [2171] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(376), 1,
      anon_sym_RBRACE,
  [2178] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(378), 1,
      sym_ident,
  [2185] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(380), 1,
      anon_sym_fn,
  [2192] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(382), 1,
      anon_sym_LBRACE,
  [2199] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(384), 1,
      sym_ident,
  [2206] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(386), 1,
      anon_sym_LBRACE,
  [2213] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(388), 1,
      anon_sym_RPAREN,
  [2220] = 2,
    ACTIONS(23), 1,
      sym_line_comment,
    ACTIONS(390), 1,
      sym_ident,
  [2227] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(392), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 45,
  [SMALL_STATE(4)] = 77,
  [SMALL_STATE(5)] = 115,
  [SMALL_STATE(6)] = 153,
  [SMALL_STATE(7)] = 176,
  [SMALL_STATE(8)] = 208,
  [SMALL_STATE(9)] = 238,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 294,
  [SMALL_STATE(12)] = 326,
  [SMALL_STATE(13)] = 355,
  [SMALL_STATE(14)] = 372,
  [SMALL_STATE(15)] = 401,
  [SMALL_STATE(16)] = 430,
  [SMALL_STATE(17)] = 447,
  [SMALL_STATE(18)] = 464,
  [SMALL_STATE(19)] = 493,
  [SMALL_STATE(20)] = 510,
  [SMALL_STATE(21)] = 527,
  [SMALL_STATE(22)] = 544,
  [SMALL_STATE(23)] = 567,
  [SMALL_STATE(24)] = 596,
  [SMALL_STATE(25)] = 625,
  [SMALL_STATE(26)] = 654,
  [SMALL_STATE(27)] = 671,
  [SMALL_STATE(28)] = 700,
  [SMALL_STATE(29)] = 729,
  [SMALL_STATE(30)] = 758,
  [SMALL_STATE(31)] = 787,
  [SMALL_STATE(32)] = 816,
  [SMALL_STATE(33)] = 845,
  [SMALL_STATE(34)] = 874,
  [SMALL_STATE(35)] = 903,
  [SMALL_STATE(36)] = 932,
  [SMALL_STATE(37)] = 961,
  [SMALL_STATE(38)] = 990,
  [SMALL_STATE(39)] = 1007,
  [SMALL_STATE(40)] = 1036,
  [SMALL_STATE(41)] = 1065,
  [SMALL_STATE(42)] = 1081,
  [SMALL_STATE(43)] = 1097,
  [SMALL_STATE(44)] = 1113,
  [SMALL_STATE(45)] = 1129,
  [SMALL_STATE(46)] = 1145,
  [SMALL_STATE(47)] = 1170,
  [SMALL_STATE(48)] = 1195,
  [SMALL_STATE(49)] = 1212,
  [SMALL_STATE(50)] = 1229,
  [SMALL_STATE(51)] = 1243,
  [SMALL_STATE(52)] = 1257,
  [SMALL_STATE(53)] = 1271,
  [SMALL_STATE(54)] = 1285,
  [SMALL_STATE(55)] = 1299,
  [SMALL_STATE(56)] = 1313,
  [SMALL_STATE(57)] = 1327,
  [SMALL_STATE(58)] = 1341,
  [SMALL_STATE(59)] = 1355,
  [SMALL_STATE(60)] = 1372,
  [SMALL_STATE(61)] = 1389,
  [SMALL_STATE(62)] = 1406,
  [SMALL_STATE(63)] = 1423,
  [SMALL_STATE(64)] = 1437,
  [SMALL_STATE(65)] = 1453,
  [SMALL_STATE(66)] = 1467,
  [SMALL_STATE(67)] = 1481,
  [SMALL_STATE(68)] = 1495,
  [SMALL_STATE(69)] = 1509,
  [SMALL_STATE(70)] = 1525,
  [SMALL_STATE(71)] = 1539,
  [SMALL_STATE(72)] = 1553,
  [SMALL_STATE(73)] = 1563,
  [SMALL_STATE(74)] = 1573,
  [SMALL_STATE(75)] = 1587,
  [SMALL_STATE(76)] = 1597,
  [SMALL_STATE(77)] = 1611,
  [SMALL_STATE(78)] = 1625,
  [SMALL_STATE(79)] = 1638,
  [SMALL_STATE(80)] = 1651,
  [SMALL_STATE(81)] = 1662,
  [SMALL_STATE(82)] = 1673,
  [SMALL_STATE(83)] = 1686,
  [SMALL_STATE(84)] = 1697,
  [SMALL_STATE(85)] = 1710,
  [SMALL_STATE(86)] = 1723,
  [SMALL_STATE(87)] = 1736,
  [SMALL_STATE(88)] = 1749,
  [SMALL_STATE(89)] = 1762,
  [SMALL_STATE(90)] = 1775,
  [SMALL_STATE(91)] = 1788,
  [SMALL_STATE(92)] = 1801,
  [SMALL_STATE(93)] = 1814,
  [SMALL_STATE(94)] = 1827,
  [SMALL_STATE(95)] = 1840,
  [SMALL_STATE(96)] = 1851,
  [SMALL_STATE(97)] = 1861,
  [SMALL_STATE(98)] = 1871,
  [SMALL_STATE(99)] = 1879,
  [SMALL_STATE(100)] = 1887,
  [SMALL_STATE(101)] = 1895,
  [SMALL_STATE(102)] = 1905,
  [SMALL_STATE(103)] = 1913,
  [SMALL_STATE(104)] = 1921,
  [SMALL_STATE(105)] = 1931,
  [SMALL_STATE(106)] = 1939,
  [SMALL_STATE(107)] = 1949,
  [SMALL_STATE(108)] = 1957,
  [SMALL_STATE(109)] = 1965,
  [SMALL_STATE(110)] = 1975,
  [SMALL_STATE(111)] = 1983,
  [SMALL_STATE(112)] = 1993,
  [SMALL_STATE(113)] = 2001,
  [SMALL_STATE(114)] = 2009,
  [SMALL_STATE(115)] = 2019,
  [SMALL_STATE(116)] = 2029,
  [SMALL_STATE(117)] = 2037,
  [SMALL_STATE(118)] = 2045,
  [SMALL_STATE(119)] = 2052,
  [SMALL_STATE(120)] = 2059,
  [SMALL_STATE(121)] = 2066,
  [SMALL_STATE(122)] = 2073,
  [SMALL_STATE(123)] = 2080,
  [SMALL_STATE(124)] = 2087,
  [SMALL_STATE(125)] = 2094,
  [SMALL_STATE(126)] = 2101,
  [SMALL_STATE(127)] = 2108,
  [SMALL_STATE(128)] = 2115,
  [SMALL_STATE(129)] = 2122,
  [SMALL_STATE(130)] = 2129,
  [SMALL_STATE(131)] = 2136,
  [SMALL_STATE(132)] = 2143,
  [SMALL_STATE(133)] = 2150,
  [SMALL_STATE(134)] = 2157,
  [SMALL_STATE(135)] = 2164,
  [SMALL_STATE(136)] = 2171,
  [SMALL_STATE(137)] = 2178,
  [SMALL_STATE(138)] = 2185,
  [SMALL_STATE(139)] = 2192,
  [SMALL_STATE(140)] = 2199,
  [SMALL_STATE(141)] = 2206,
  [SMALL_STATE(142)] = 2213,
  [SMALL_STATE(143)] = 2220,
  [SMALL_STATE(144)] = 2227,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 1),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(27),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(24),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(23),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(20),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(67),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 2),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2), SHIFT_REPEAT(64),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [71] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(138),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(137),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(144),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(97),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 4),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 4),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 3),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 3),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 3),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 3),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 2),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 2),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(144),
  [158] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(90),
  [161] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(92),
  [164] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(97),
  [167] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(70),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 7),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 7),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 2),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 2),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 3),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 4),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 2),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 2),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 3),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 4),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 4),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, .production_id = 1),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2, .production_id = 1),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 4),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 6),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 6),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 5),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 5),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(120),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [231] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(81),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [238] = {.entry = {.count = 1, .reusable = false}}, SHIFT(81),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [248] = {.entry = {.count = 1, .reusable = false}}, SHIFT(69),
  [250] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat1, 2), SHIFT_REPEAT(69),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2),
  [265] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2), SHIFT_REPEAT(68),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, .production_id = 2),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 1, .production_id = 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [294] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(140),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [299] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 1),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 1),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2),
  [319] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2), SHIFT_REPEAT(35),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [328] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 5),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [336] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 2, .production_id = 2),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 2, .production_id = 2),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(123),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [354] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [358] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [360] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 3),
  [362] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [370] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [374] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [378] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [380] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [384] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [386] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [388] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [390] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [392] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_chirp_external_scanner_create(void);
void tree_sitter_chirp_external_scanner_destroy(void *);
bool tree_sitter_chirp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_chirp_external_scanner_serialize(void *, char *);
void tree_sitter_chirp_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chirp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_chirp_external_scanner_create,
      tree_sitter_chirp_external_scanner_destroy,
      tree_sitter_chirp_external_scanner_scan,
      tree_sitter_chirp_external_scanner_serialize,
      tree_sitter_chirp_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
