#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 141
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 43
#define ALIAS_COUNT 2
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define PRODUCTION_ID_COUNT 3

enum {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACK = 3,
  anon_sym_RBRACK = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_COMMA = 7,
  anon_sym_code = 8,
  anon_sym_Entity = 9,
  anon_sym_as = 10,
  anon_sym_use = 11,
  anon_sym_pub = 12,
  anon_sym_fn = 13,
  sym_ident = 14,
  sym_template_call_ident = 15,
  anon_sym_DQUOTE = 16,
  anon_sym_DQUOTE2 = 17,
  sym_escape_sequence = 18,
  sym_line_comment = 19,
  sym__string_content = 20,
  sym_chirp_file = 21,
  sym__token_tree = 22,
  sym_argument = 23,
  sym__arguments = 24,
  sym_method = 25,
  sym_statement = 26,
  sym__statement_tail = 27,
  sym_path = 28,
  sym_import_item = 29,
  sym_import = 30,
  sym_parameters = 31,
  sym_fn = 32,
  sym_string_lit = 33,
  aux_sym_chirp_file_repeat1 = 34,
  aux_sym_chirp_file_repeat2 = 35,
  aux_sym__token_tree_repeat1 = 36,
  aux_sym__arguments_repeat1 = 37,
  aux_sym__statement_tail_repeat1 = 38,
  aux_sym__statement_tail_repeat2 = 39,
  aux_sym_import_repeat1 = 40,
  aux_sym_parameters_repeat1 = 41,
  aux_sym_string_lit_repeat1 = 42,
  anon_alias_sym_ident = 43,
  anon_alias_sym_string_lit = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [anon_sym_code] = "code",
  [anon_sym_Entity] = "Entity",
  [anon_sym_as] = "as",
  [anon_sym_use] = "use",
  [anon_sym_pub] = "pub",
  [anon_sym_fn] = "fn",
  [sym_ident] = "ident",
  [sym_template_call_ident] = "template_call_ident",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_DQUOTE2] = "\"",
  [sym_escape_sequence] = "escape_sequence",
  [sym_line_comment] = "line_comment",
  [sym__string_content] = "_string_content",
  [sym_chirp_file] = "chirp_file",
  [sym__token_tree] = "_token_tree",
  [sym_argument] = "argument",
  [sym__arguments] = "_arguments",
  [sym_method] = "method",
  [sym_statement] = "statement",
  [sym__statement_tail] = "_statement_tail",
  [sym_path] = "path",
  [sym_import_item] = "import_item",
  [sym_import] = "import",
  [sym_parameters] = "parameters",
  [sym_fn] = "fn",
  [sym_string_lit] = "string_lit",
  [aux_sym_chirp_file_repeat1] = "chirp_file_repeat1",
  [aux_sym_chirp_file_repeat2] = "chirp_file_repeat2",
  [aux_sym__token_tree_repeat1] = "_token_tree_repeat1",
  [aux_sym__arguments_repeat1] = "_arguments_repeat1",
  [aux_sym__statement_tail_repeat1] = "_statement_tail_repeat1",
  [aux_sym__statement_tail_repeat2] = "_statement_tail_repeat2",
  [aux_sym_import_repeat1] = "import_repeat1",
  [aux_sym_parameters_repeat1] = "parameters_repeat1",
  [aux_sym_string_lit_repeat1] = "string_lit_repeat1",
  [anon_alias_sym_ident] = "ident",
  [anon_alias_sym_string_lit] = "string_lit",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_code] = anon_sym_code,
  [anon_sym_Entity] = anon_sym_Entity,
  [anon_sym_as] = anon_sym_as,
  [anon_sym_use] = anon_sym_use,
  [anon_sym_pub] = anon_sym_pub,
  [anon_sym_fn] = anon_sym_fn,
  [sym_ident] = sym_ident,
  [sym_template_call_ident] = sym_template_call_ident,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_DQUOTE2] = anon_sym_DQUOTE,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_line_comment] = sym_line_comment,
  [sym__string_content] = sym__string_content,
  [sym_chirp_file] = sym_chirp_file,
  [sym__token_tree] = sym__token_tree,
  [sym_argument] = sym_argument,
  [sym__arguments] = sym__arguments,
  [sym_method] = sym_method,
  [sym_statement] = sym_statement,
  [sym__statement_tail] = sym__statement_tail,
  [sym_path] = sym_path,
  [sym_import_item] = sym_import_item,
  [sym_import] = sym_import,
  [sym_parameters] = sym_parameters,
  [sym_fn] = sym_fn,
  [sym_string_lit] = sym_string_lit,
  [aux_sym_chirp_file_repeat1] = aux_sym_chirp_file_repeat1,
  [aux_sym_chirp_file_repeat2] = aux_sym_chirp_file_repeat2,
  [aux_sym__token_tree_repeat1] = aux_sym__token_tree_repeat1,
  [aux_sym__arguments_repeat1] = aux_sym__arguments_repeat1,
  [aux_sym__statement_tail_repeat1] = aux_sym__statement_tail_repeat1,
  [aux_sym__statement_tail_repeat2] = aux_sym__statement_tail_repeat2,
  [aux_sym_import_repeat1] = aux_sym_import_repeat1,
  [aux_sym_parameters_repeat1] = aux_sym_parameters_repeat1,
  [aux_sym_string_lit_repeat1] = aux_sym_string_lit_repeat1,
  [anon_alias_sym_ident] = anon_alias_sym_ident,
  [anon_alias_sym_string_lit] = anon_alias_sym_string_lit,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_code] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Entity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_as] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_use] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_pub] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_template_call_ident] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE2] = {
    .visible = true,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [sym_chirp_file] = {
    .visible = true,
    .named = true,
  },
  [sym__token_tree] = {
    .visible = false,
    .named = true,
  },
  [sym_argument] = {
    .visible = true,
    .named = true,
  },
  [sym__arguments] = {
    .visible = false,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_tail] = {
    .visible = false,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_import_item] = {
    .visible = true,
    .named = true,
  },
  [sym_import] = {
    .visible = true,
    .named = true,
  },
  [sym_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_fn] = {
    .visible = true,
    .named = true,
  },
  [sym_string_lit] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_chirp_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_chirp_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__token_tree_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__arguments_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__statement_tail_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_import_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_lit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_ident] = {
    .visible = true,
    .named = false,
  },
  [anon_alias_sym_string_lit] = {
    .visible = true,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = anon_alias_sym_ident,
  },
  [2] = {
    [0] = anon_alias_sym_string_lit,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  sym_string_lit, 2,
    sym_string_lit,
    anon_alias_sym_string_lit,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 7,
  [11] = 7,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 17,
  [32] = 16,
  [33] = 33,
  [34] = 27,
  [35] = 33,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 28,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 22,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 45,
  [69] = 69,
  [70] = 44,
  [71] = 64,
  [72] = 72,
  [73] = 73,
  [74] = 69,
  [75] = 43,
  [76] = 66,
  [77] = 48,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 79,
  [82] = 80,
  [83] = 83,
  [84] = 84,
  [85] = 47,
  [86] = 84,
  [87] = 87,
  [88] = 88,
  [89] = 79,
  [90] = 84,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 45,
  [95] = 19,
  [96] = 53,
  [97] = 57,
  [98] = 98,
  [99] = 52,
  [100] = 54,
  [101] = 101,
  [102] = 21,
  [103] = 103,
  [104] = 104,
  [105] = 101,
  [106] = 43,
  [107] = 56,
  [108] = 55,
  [109] = 109,
  [110] = 50,
  [111] = 51,
  [112] = 44,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 115,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 119,
  [140] = 126,
};

static inline bool sym_ident_character_set_1(int32_t c) {
  return (c < ','
    ? (c < '\r'
      ? (c < '\t'
        ? c == 0
        : c <= '\n')
      : (c <= '\r' || (c < '\''
        ? (c >= ' ' && c <= '"')
        : c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static inline bool sym_line_comment_character_set_1(int32_t c) {
  return (c < ','
    ? (c < ' '
      ? (c < '\r'
        ? c == '\t'
        : c <= '\r')
      : (c <= '"' || (c >= '\'' && c <= ')')))
    : (c <= ',' || (c < '{'
      ? (c < ']'
        ? c == '['
        : c <= ']')
      : (c <= '{' || c == '}'))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(71);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(18);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(65);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '\'') ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']') ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(73);
      END_STATE();
    case 6:
      if (lookahead == 'b') ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(43);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(38);
      END_STATE();
    case 10:
      if (lookahead == 'i') ADVANCE(17);
      END_STATE();
    case 11:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 12:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 14:
      if (lookahead == 's') ADVANCE(42);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == 'x') ADVANCE(26);
      if (lookahead != 0) ADVANCE(72);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(6);
      END_STATE();
    case 20:
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == '{') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == '}') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 24:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 25:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      END_STATE();
    case 27:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == 'E') ADVANCE(11);
      if (lookahead == '[') ADVANCE(33);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(13);
      if (lookahead == 'f') ADVANCE(12);
      if (lookahead == 'p') ADVANCE(19);
      if (lookahead == 'u') ADVANCE(15);
      if (lookahead == '{') ADVANCE(35);
      if (lookahead == '}') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(27)
      END_STATE();
    case 28:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == 'u') ADVANCE(58);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(28)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 29:
      if (eof) ADVANCE(30);
      if (lookahead == '"') ADVANCE(70);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == 'E') ADVANCE(55);
      if (lookahead == 'c') ADVANCE(57);
      if (lookahead == 'f') ADVANCE(56);
      if (lookahead == 'p') ADVANCE(61);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(29)
      if (lookahead != 0 &&
          lookahead != '!' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != ',' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(63);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_code);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_code);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Entity);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_Entity);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_as);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_use);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_use);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_pub);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_pub);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_fn);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == '/') ADVANCE(64);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'b') ADVANCE(46);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'd') ADVANCE(53);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(44);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'e') ADVANCE(39);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(60);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(59);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(48);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'o') ADVANCE(51);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 's') ADVANCE(52);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(54);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 't') ADVANCE(62);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'u') ADVANCE(50);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (lookahead == 'y') ADVANCE(41);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(68);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '!') ADVANCE(69);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '/') ADVANCE(66);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (sym_line_comment_character_set_1(lookahead)) ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (!sym_ident_character_set_1(lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_template_call_ident);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_template_call_ident);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_DQUOTE2);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 28},
  [2] = {.lex_state = 28},
  [3] = {.lex_state = 29},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 29},
  [6] = {.lex_state = 28},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 29},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 28},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 28},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 29},
  [42] = {.lex_state = 29},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 3},
  [46] = {.lex_state = 3},
  [47] = {.lex_state = 3},
  [48] = {.lex_state = 3},
  [49] = {.lex_state = 3},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 3},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 3},
  [54] = {.lex_state = 3},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 1, .external_lex_state = 1},
  [64] = {.lex_state = 1, .external_lex_state = 1},
  [65] = {.lex_state = 1, .external_lex_state = 1},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 1, .external_lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 1, .external_lex_state = 1},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 2},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 2},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 2},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 2},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 2},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 2},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 2},
  [133] = {.lex_state = 2},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 2},
  [140] = {.lex_state = 0},
};

enum {
  ts_external_token__string_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__string_content] = sym__string_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__string_content] = true,
  },
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_code] = ACTIONS(1),
    [anon_sym_Entity] = ACTIONS(1),
    [anon_sym_as] = ACTIONS(1),
    [anon_sym_use] = ACTIONS(1),
    [anon_sym_pub] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym__string_content] = ACTIONS(1),
  },
  [1] = {
    [sym_chirp_file] = STATE(125),
    [sym_statement] = STATE(124),
    [sym_import] = STATE(2),
    [sym_fn] = STATE(3),
    [sym_string_lit] = STATE(82),
    [aux_sym_chirp_file_repeat1] = STATE(2),
    [aux_sym_chirp_file_repeat2] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_code] = ACTIONS(7),
    [anon_sym_Entity] = ACTIONS(9),
    [anon_sym_use] = ACTIONS(11),
    [anon_sym_pub] = ACTIONS(13),
    [anon_sym_fn] = ACTIONS(15),
    [sym_ident] = ACTIONS(9),
    [sym_template_call_ident] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(11), 1,
      anon_sym_use,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_template_call_ident,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(82), 1,
      sym_string_lit,
    STATE(138), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(5), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
  [43] = 11,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_template_call_ident,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(82), 1,
      sym_string_lit,
    STATE(138), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [79] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(25), 1,
      anon_sym_LPAREN,
    ACTIONS(30), 1,
      anon_sym_LBRACK,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      sym_ident,
    ACTIONS(39), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string_lit,
    STATE(4), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
    ACTIONS(28), 4,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COMMA,
  [111] = 11,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(13), 1,
      anon_sym_pub,
    ACTIONS(15), 1,
      anon_sym_fn,
    ACTIONS(17), 1,
      sym_template_call_ident,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    STATE(82), 1,
      sym_string_lit,
    STATE(137), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
  [147] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(48), 1,
      anon_sym_use,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(6), 2,
      sym_import,
      aux_sym_chirp_file_repeat1,
    ACTIONS(46), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [170] = 10,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string_lit,
    STATE(86), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [202] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string_lit,
    ACTIONS(63), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    STATE(4), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [232] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(69), 1,
      anon_sym_pub,
    ACTIONS(72), 1,
      anon_sym_fn,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    STATE(9), 2,
      sym_fn,
      aux_sym_chirp_file_repeat2,
    ACTIONS(67), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [256] = 10,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_string_lit,
    STATE(84), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [288] = 10,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_string_lit,
    STATE(90), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [320] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    STATE(18), 1,
      sym_string_lit,
    STATE(109), 1,
      sym_argument,
    STATE(8), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [349] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(79), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(81), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [366] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(85), 1,
      sym_ident,
    ACTIONS(83), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [383] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_string_lit,
    STATE(4), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [412] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(26), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [439] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(97), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(34), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [466] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(101), 1,
      sym_ident,
    ACTIONS(99), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [483] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(105), 1,
      sym_ident,
    ACTIONS(103), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [500] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(107), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(109), 7,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_use,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [517] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(113), 1,
      sym_ident,
    ACTIONS(111), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [534] = 6,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(52), 1,
      sym__statement_tail,
    ACTIONS(119), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(121), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [557] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(125), 1,
      sym_ident,
    ACTIONS(123), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [574] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      sym_string_lit,
    STATE(37), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [603] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(129), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [630] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(131), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [657] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(133), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [684] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(135), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(35), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [711] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(139), 1,
      sym_ident,
    ACTIONS(137), 8,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COMMA,
      anon_sym_DQUOTE,
  [728] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_RBRACK,
    STATE(18), 1,
      sym_string_lit,
    STATE(15), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [757] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(141), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(27), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [784] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(25), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [811] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(143), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [838] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(145), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [865] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(89), 1,
      anon_sym_RBRACE,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [892] = 8,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    ACTIONS(149), 1,
      anon_sym_code,
    ACTIONS(155), 1,
      sym_template_call_ident,
    ACTIONS(158), 1,
      anon_sym_DQUOTE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(152), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(36), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [919] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_RBRACE,
    STATE(18), 1,
      sym_string_lit,
    STATE(4), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [948] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(87), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_string_lit,
    STATE(4), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [977] = 9,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(51), 1,
      anon_sym_LPAREN,
    ACTIONS(55), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    ACTIONS(59), 1,
      sym_ident,
    ACTIONS(61), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_RPAREN,
    STATE(18), 1,
      sym_string_lit,
    STATE(38), 2,
      sym__token_tree,
      aux_sym__token_tree_repeat1,
  [1006] = 8,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(91), 1,
      anon_sym_code,
    ACTIONS(95), 1,
      sym_template_call_ident,
    ACTIONS(161), 1,
      anon_sym_RBRACE,
    STATE(80), 1,
      sym_string_lit,
    ACTIONS(93), 2,
      anon_sym_Entity,
      sym_ident,
    STATE(33), 2,
      sym_statement,
      aux_sym__statement_tail_repeat2,
  [1033] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(163), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(165), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1049] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
    ACTIONS(169), 6,
      anon_sym_code,
      anon_sym_Entity,
      anon_sym_pub,
      anon_sym_fn,
      sym_ident,
      sym_template_call_ident,
  [1065] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(171), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(173), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1081] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(175), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(177), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1097] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(179), 4,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(181), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1113] = 7,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(17), 1,
      sym_template_call_ident,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(82), 1,
      sym_string_lit,
    STATE(135), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_Entity,
      sym_ident,
  [1136] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(183), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(187), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1153] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(189), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(193), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1170] = 7,
    ACTIONS(7), 1,
      anon_sym_code,
    ACTIONS(17), 1,
      sym_template_call_ident,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    STATE(82), 1,
      sym_string_lit,
    STATE(118), 1,
      sym_statement,
    ACTIONS(9), 2,
      anon_sym_Entity,
      sym_ident,
  [1193] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(185), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(187), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1207] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(119), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(121), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1221] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(195), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(197), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1235] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(199), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(201), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1249] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(191), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(193), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1263] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(203), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(205), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1277] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(207), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(209), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1291] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(211), 2,
      anon_sym_RBRACE,
      anon_sym_DQUOTE,
    ACTIONS(213), 4,
      anon_sym_code,
      anon_sym_Entity,
      sym_ident,
      sym_template_call_ident,
  [1305] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
    ACTIONS(219), 1,
      sym_ident,
    STATE(60), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1322] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(221), 1,
      anon_sym_LPAREN,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
    STATE(99), 1,
      sym__statement_tail,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1339] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(225), 1,
      anon_sym_LPAREN,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    ACTIONS(230), 1,
      sym_ident,
    STATE(60), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1356] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(215), 1,
      anon_sym_LPAREN,
    ACTIONS(219), 1,
      sym_ident,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
    STATE(58), 2,
      sym_import_item,
      aux_sym_import_repeat1,
  [1373] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(235), 1,
      anon_sym_RPAREN,
    ACTIONS(237), 1,
      sym_ident,
    STATE(62), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1387] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(240), 1,
      anon_sym_DQUOTE2,
    STATE(63), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(242), 2,
      sym__string_content,
      sym_escape_sequence,
  [1401] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(245), 1,
      anon_sym_DQUOTE2,
    STATE(65), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(247), 2,
      sym__string_content,
      sym_escape_sequence,
  [1415] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(249), 1,
      anon_sym_DQUOTE2,
    STATE(63), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(251), 2,
      sym__string_content,
      sym_escape_sequence,
  [1429] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(253), 1,
      anon_sym_RPAREN,
    ACTIONS(255), 1,
      sym_ident,
    STATE(62), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1443] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(257), 1,
      anon_sym_DQUOTE2,
    STATE(63), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(251), 2,
      sym__string_content,
      sym_escape_sequence,
  [1457] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(179), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1467] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(255), 1,
      sym_ident,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    STATE(66), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1481] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(175), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1491] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(261), 1,
      anon_sym_DQUOTE2,
    STATE(67), 1,
      aux_sym_string_lit_repeat1,
    ACTIONS(263), 2,
      sym__string_content,
      sym_escape_sequence,
  [1505] = 5,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(265), 1,
      sym_ident,
    STATE(120), 1,
      sym_string_lit,
    STATE(121), 1,
      sym_path,
  [1521] = 5,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(267), 1,
      anon_sym_LPAREN,
    ACTIONS(269), 1,
      anon_sym_RPAREN,
    ACTIONS(271), 1,
      sym_ident,
    STATE(98), 1,
      sym__arguments,
  [1537] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(255), 1,
      sym_ident,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    STATE(76), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1551] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(171), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1561] = 4,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(255), 1,
      sym_ident,
    ACTIONS(275), 1,
      anon_sym_RPAREN,
    STATE(62), 2,
      sym_method,
      aux_sym__statement_tail_repeat1,
  [1575] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(277), 1,
      anon_sym_LBRACE,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1586] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(279), 1,
      anon_sym_RPAREN,
    ACTIONS(281), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_parameters_repeat1,
  [1599] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(284), 1,
      anon_sym_RPAREN,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym__arguments_repeat1,
  [1612] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(115), 1,
      anon_sym_LPAREN,
    ACTIONS(117), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym__statement_tail,
  [1625] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(288), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym__arguments_repeat1,
  [1638] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(221), 1,
      anon_sym_LPAREN,
    ACTIONS(223), 1,
      anon_sym_LBRACE,
    STATE(111), 1,
      sym__statement_tail,
  [1651] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(290), 1,
      anon_sym_RPAREN,
    ACTIONS(292), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      aux_sym_parameters_repeat1,
  [1664] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      aux_sym__arguments_repeat1,
  [1677] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(296), 1,
      anon_sym_LBRACE,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1688] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(298), 1,
      anon_sym_RPAREN,
    STATE(89), 1,
      aux_sym__arguments_repeat1,
  [1701] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(292), 1,
      anon_sym_COMMA,
    ACTIONS(300), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      aux_sym_parameters_repeat1,
  [1714] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    ACTIONS(304), 1,
      anon_sym_COMMA,
    STATE(88), 1,
      aux_sym__arguments_repeat1,
  [1727] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(307), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      aux_sym__arguments_repeat1,
  [1740] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(286), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RPAREN,
    STATE(81), 1,
      aux_sym__arguments_repeat1,
  [1753] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(313), 1,
      sym_ident,
    ACTIONS(311), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1764] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(317), 1,
      sym_ident,
    ACTIONS(315), 2,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
  [1775] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(319), 1,
      anon_sym_LPAREN,
    STATE(129), 1,
      sym_parameters,
  [1785] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
    ACTIONS(181), 1,
      sym_ident,
  [1795] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(103), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1803] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(199), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1811] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(211), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1819] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(321), 1,
      anon_sym_RPAREN,
    ACTIONS(323), 1,
      sym_ident,
  [1829] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(195), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1837] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(191), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1845] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(325), 1,
      anon_sym_LPAREN,
    STATE(59), 1,
      sym__arguments,
  [1855] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(111), 2,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
  [1863] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(327), 1,
      anon_sym_RPAREN,
    ACTIONS(329), 1,
      sym_ident,
  [1873] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(319), 1,
      anon_sym_LPAREN,
    STATE(122), 1,
      sym_parameters,
  [1883] = 3,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(331), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym__arguments,
  [1893] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(171), 1,
      anon_sym_RPAREN,
    ACTIONS(173), 1,
      sym_ident,
  [1903] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(207), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1911] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(203), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1919] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(302), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1927] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(185), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1935] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
  [1943] = 3,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
    ACTIONS(177), 1,
      sym_ident,
  [1953] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(279), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1961] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(333), 1,
      anon_sym_as,
  [1968] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(335), 1,
      anon_sym_RPAREN,
  [1975] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(337), 1,
      anon_sym_LBRACE,
  [1982] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(339), 1,
      anon_sym_LBRACE,
  [1989] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(341), 1,
      anon_sym_RBRACE,
  [1996] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(343), 1,
      sym_ident,
  [2003] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(345), 1,
      anon_sym_LPAREN,
  [2010] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(347), 1,
      anon_sym_LPAREN,
  [2017] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(349), 1,
      anon_sym_LBRACE,
  [2024] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(351), 1,
      sym_ident,
  [2031] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
  [2038] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(353), 1,
      ts_builtin_sym_end,
  [2045] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(355), 1,
      anon_sym_LPAREN,
  [2052] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(357), 1,
      sym_ident,
  [2059] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(359), 1,
      anon_sym_LBRACE,
  [2066] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(361), 1,
      anon_sym_LBRACE,
  [2073] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(363), 1,
      sym_ident,
  [2080] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(365), 1,
      anon_sym_RPAREN,
  [2087] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(367), 1,
      sym_ident,
  [2094] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(369), 1,
      sym_ident,
  [2101] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(371), 1,
      anon_sym_fn,
  [2108] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(373), 1,
      anon_sym_RBRACE,
  [2115] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(375), 1,
      anon_sym_RPAREN,
  [2122] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(377), 1,
      ts_builtin_sym_end,
  [2129] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
  [2136] = 2,
    ACTIONS(21), 1,
      sym_line_comment,
    ACTIONS(379), 1,
      sym_ident,
  [2143] = 2,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(381), 1,
      anon_sym_LPAREN,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 43,
  [SMALL_STATE(4)] = 79,
  [SMALL_STATE(5)] = 111,
  [SMALL_STATE(6)] = 147,
  [SMALL_STATE(7)] = 170,
  [SMALL_STATE(8)] = 202,
  [SMALL_STATE(9)] = 232,
  [SMALL_STATE(10)] = 256,
  [SMALL_STATE(11)] = 288,
  [SMALL_STATE(12)] = 320,
  [SMALL_STATE(13)] = 349,
  [SMALL_STATE(14)] = 366,
  [SMALL_STATE(15)] = 383,
  [SMALL_STATE(16)] = 412,
  [SMALL_STATE(17)] = 439,
  [SMALL_STATE(18)] = 466,
  [SMALL_STATE(19)] = 483,
  [SMALL_STATE(20)] = 500,
  [SMALL_STATE(21)] = 517,
  [SMALL_STATE(22)] = 534,
  [SMALL_STATE(23)] = 557,
  [SMALL_STATE(24)] = 574,
  [SMALL_STATE(25)] = 603,
  [SMALL_STATE(26)] = 630,
  [SMALL_STATE(27)] = 657,
  [SMALL_STATE(28)] = 684,
  [SMALL_STATE(29)] = 711,
  [SMALL_STATE(30)] = 728,
  [SMALL_STATE(31)] = 757,
  [SMALL_STATE(32)] = 784,
  [SMALL_STATE(33)] = 811,
  [SMALL_STATE(34)] = 838,
  [SMALL_STATE(35)] = 865,
  [SMALL_STATE(36)] = 892,
  [SMALL_STATE(37)] = 919,
  [SMALL_STATE(38)] = 948,
  [SMALL_STATE(39)] = 977,
  [SMALL_STATE(40)] = 1006,
  [SMALL_STATE(41)] = 1033,
  [SMALL_STATE(42)] = 1049,
  [SMALL_STATE(43)] = 1065,
  [SMALL_STATE(44)] = 1081,
  [SMALL_STATE(45)] = 1097,
  [SMALL_STATE(46)] = 1113,
  [SMALL_STATE(47)] = 1136,
  [SMALL_STATE(48)] = 1153,
  [SMALL_STATE(49)] = 1170,
  [SMALL_STATE(50)] = 1193,
  [SMALL_STATE(51)] = 1207,
  [SMALL_STATE(52)] = 1221,
  [SMALL_STATE(53)] = 1235,
  [SMALL_STATE(54)] = 1249,
  [SMALL_STATE(55)] = 1263,
  [SMALL_STATE(56)] = 1277,
  [SMALL_STATE(57)] = 1291,
  [SMALL_STATE(58)] = 1305,
  [SMALL_STATE(59)] = 1322,
  [SMALL_STATE(60)] = 1339,
  [SMALL_STATE(61)] = 1356,
  [SMALL_STATE(62)] = 1373,
  [SMALL_STATE(63)] = 1387,
  [SMALL_STATE(64)] = 1401,
  [SMALL_STATE(65)] = 1415,
  [SMALL_STATE(66)] = 1429,
  [SMALL_STATE(67)] = 1443,
  [SMALL_STATE(68)] = 1457,
  [SMALL_STATE(69)] = 1467,
  [SMALL_STATE(70)] = 1481,
  [SMALL_STATE(71)] = 1491,
  [SMALL_STATE(72)] = 1505,
  [SMALL_STATE(73)] = 1521,
  [SMALL_STATE(74)] = 1537,
  [SMALL_STATE(75)] = 1551,
  [SMALL_STATE(76)] = 1561,
  [SMALL_STATE(77)] = 1575,
  [SMALL_STATE(78)] = 1586,
  [SMALL_STATE(79)] = 1599,
  [SMALL_STATE(80)] = 1612,
  [SMALL_STATE(81)] = 1625,
  [SMALL_STATE(82)] = 1638,
  [SMALL_STATE(83)] = 1651,
  [SMALL_STATE(84)] = 1664,
  [SMALL_STATE(85)] = 1677,
  [SMALL_STATE(86)] = 1688,
  [SMALL_STATE(87)] = 1701,
  [SMALL_STATE(88)] = 1714,
  [SMALL_STATE(89)] = 1727,
  [SMALL_STATE(90)] = 1740,
  [SMALL_STATE(91)] = 1753,
  [SMALL_STATE(92)] = 1764,
  [SMALL_STATE(93)] = 1775,
  [SMALL_STATE(94)] = 1785,
  [SMALL_STATE(95)] = 1795,
  [SMALL_STATE(96)] = 1803,
  [SMALL_STATE(97)] = 1811,
  [SMALL_STATE(98)] = 1819,
  [SMALL_STATE(99)] = 1829,
  [SMALL_STATE(100)] = 1837,
  [SMALL_STATE(101)] = 1845,
  [SMALL_STATE(102)] = 1855,
  [SMALL_STATE(103)] = 1863,
  [SMALL_STATE(104)] = 1873,
  [SMALL_STATE(105)] = 1883,
  [SMALL_STATE(106)] = 1893,
  [SMALL_STATE(107)] = 1903,
  [SMALL_STATE(108)] = 1911,
  [SMALL_STATE(109)] = 1919,
  [SMALL_STATE(110)] = 1927,
  [SMALL_STATE(111)] = 1935,
  [SMALL_STATE(112)] = 1943,
  [SMALL_STATE(113)] = 1953,
  [SMALL_STATE(114)] = 1961,
  [SMALL_STATE(115)] = 1968,
  [SMALL_STATE(116)] = 1975,
  [SMALL_STATE(117)] = 1982,
  [SMALL_STATE(118)] = 1989,
  [SMALL_STATE(119)] = 1996,
  [SMALL_STATE(120)] = 2003,
  [SMALL_STATE(121)] = 2010,
  [SMALL_STATE(122)] = 2017,
  [SMALL_STATE(123)] = 2024,
  [SMALL_STATE(124)] = 2031,
  [SMALL_STATE(125)] = 2038,
  [SMALL_STATE(126)] = 2045,
  [SMALL_STATE(127)] = 2052,
  [SMALL_STATE(128)] = 2059,
  [SMALL_STATE(129)] = 2066,
  [SMALL_STATE(130)] = 2073,
  [SMALL_STATE(131)] = 2080,
  [SMALL_STATE(132)] = 2087,
  [SMALL_STATE(133)] = 2094,
  [SMALL_STATE(134)] = 2101,
  [SMALL_STATE(135)] = 2108,
  [SMALL_STATE(136)] = 2115,
  [SMALL_STATE(137)] = 2122,
  [SMALL_STATE(138)] = 2129,
  [SMALL_STATE(139)] = 2136,
  [SMALL_STATE(140)] = 2143,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(126),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(133),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 1),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(39),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(30),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(24),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(23),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__token_tree_repeat1, 2), SHIFT_REPEAT(71),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 2),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [46] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2),
  [48] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat1, 2), SHIFT_REPEAT(72),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument, 1),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(134),
  [72] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_chirp_file_repeat2, 2), SHIFT_REPEAT(133),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 5),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 5),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 2),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 2),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 2),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 2),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import, 4),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import, 4),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_lit, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_lit, 2),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 1, .production_id = 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 1, .production_id = 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__token_tree, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__token_tree, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(140),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(80),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(105),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat2, 2), SHIFT_REPEAT(64),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 6),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 6),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn, 7),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_fn, 7),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 2),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 2),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 3),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 3),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__arguments, 4),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__arguments, 4),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 2),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 3),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 3),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 3),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 4),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 4),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 4),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 5),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 5),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement_tail, 6),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement_tail, 6),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [219] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [225] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(130),
  [228] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_import_repeat1, 2),
  [230] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_import_repeat1, 2), SHIFT_REPEAT(92),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_tail_repeat1, 2),
  [237] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_tail_repeat1, 2), SHIFT_REPEAT(73),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2),
  [242] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_lit_repeat1, 2), SHIFT_REPEAT(63),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(120),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 1),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2),
  [281] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameters_repeat1, 2), SHIFT_REPEAT(127),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2),
  [304] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__arguments_repeat1, 2), SHIFT_REPEAT(12),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 5),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 5),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_item, 1),
  [317] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_item, 1),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [321] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 2),
  [323] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_method, 2),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 3),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 4),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [343] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 1),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [351] = {.entry = {.count = 1, .reusable = false}}, SHIFT(93),
  [353] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [357] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameters, 2),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [363] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_chirp_file, 3),
  [379] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_chirp_external_scanner_create(void);
void tree_sitter_chirp_external_scanner_destroy(void *);
bool tree_sitter_chirp_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_chirp_external_scanner_serialize(void *, char *);
void tree_sitter_chirp_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_chirp(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_chirp_external_scanner_create,
      tree_sitter_chirp_external_scanner_destroy,
      tree_sitter_chirp_external_scanner_scan,
      tree_sitter_chirp_external_scanner_serialize,
      tree_sitter_chirp_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
